name: documentation site
on:
  push:
    types:
    - created

jobs:
  update:
    runs-on: ubuntu-22.04
    steps:
    - name: Pull code
      uses: actions/checkout@v1
    - name: Install dependencies
      run: npm ci --ignore-scripts
    - name: Build site
      run: npx compodoc
    - name: Publish changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx gh-pages --dist docs --repo https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git --user 'GitHub Actions <luxon-angular@stellj.es>'
