name: pull request
on:
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - name: Pull code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: npm ci
    - name: Lint
      run: npm run lint
    - name: Run unit tests
      run: npm run test -- --browsers=ChromeHeadless --watch=false
