name: release
on:
  release:
    types:
    - created

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
    - name: Pull code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: npm ci --ignore-scripts
    - name: Build
      run: npm run build -- --configuration production
    - name: Configure npm
      run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
      working-directory: ./dist/luxon-angular
    - name: Publish to npm
      run: npm publish
      working-directory: ./dist/luxon-angular
